name: CI (Tests)
run-name: ${{ github.workflow }} - ${{ github.ref }} - by ${{ github.actor }}

# events that trigger this workflow
on:
  pull_request:
    branches: [ "main", "prod" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge
        default: firefox

# jobs to be executed on runner machines
jobs:
  
  # php-tests:
  #   name: PestPHP tests + Composer migrations
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v6

  #     - name: Set up .env file
  #       working-directory: ./docker
  #       run: |
  #         cp ./demo.env ./.env
  #         echo -e "\nSELENIUM_BROWSER=${{ inputs.browser }}" >> ./.env

  #     - name: run docker compose to start the application 
  #       working-directory: ./docker
  #       run: |
  #         docker compose --profile testing up --build -d

  #     - name: Setup PHP with PECL extension
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.3'
  #         extensions: xml, mysql, cli

  #     - name: Install composer dependencies
  #       working-directory: ./src/abet_private
  #       run: |
  #         composer install --no-interaction --prefer-dist --optimize-autoloader 

  selenium-tests: 
    name: Test General Functionality
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     browser: [chrome]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up .env file
        working-directory: ./docker
        run: |
          cp ./demo.env ./.env
          echo -e "\nSELENIUM_BROWSER=${{ inputs.browser || 'firefox' }}" >> ./.env

      - name: run docker compose to start the application 
        working-directory: ./docker
        run: |
          docker compose --profile testing up --build -d
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xml, mysql, cli

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install testing dependencies
        run: |
          pip install --root-user-action=ignore -r src/test/requirements.txt > /dev/null

      - name: Install composer dependencies
        working-directory: ./src/abet_private
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader 

      - name: Wait for services to be ready 
        run: |
          # Wait for the containers to be ready
          sleep 10

      # - name: Debug screenshot
      #   uses: flameddd/screenshots-ci-action@master
      #   with:
      #     url: 

      - name: Fetch URL with wget
        run: |
          URL="http://localhost:8080/login"
          OUTPUT="response.html"

          wget \
            --max-redirect=20 \
            --output-document="$OUTPUT" \
            "$URL" | true

      - name: dump docker logs
        run: docker logs php_apache

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: fetched-response
          path: response.html

      - name: Run Selenium tests
        run: |
          # Run your Selenium tests here, for example:
          pytest src/test/

      - name: Run Pest tests
        working-directory: ./src/abet_private
        run: |
          composer test
          
      - name: Run migrations
        working-directory: ./src/abet_private
        run: |
          composer doctrine migrate --no-interaction
        
