name: Run Selenium Tests
run-name: ${{ github.workflow }} - ${{ github.ref }} - by ${{ github.actor }}

# events that trigger this workflow
on:
  # push:
  #   branches: [ dev, prod ]
  #   paths-ignore:
  #     - '*.md'
  #     - 'docs/**'
  #     - '.github/workflows/**'
  # pull_request:
  #   branches: [ dev, prod ]
  #   paths-ignore:
  #     - '*.md'
  #     - 'docs/**'
  #     - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge
        default: firefox

# jobs to be executed on runner machines
jobs:
  selenium-tests: 
    name: Test
    runs-on: ubuntu-latest

    # services:
    #   selenium:
    #     image: selenium/standalone-${{ inputs.browser }}
    #     ports:
    #       - 4444:4444
    #     options: --shm-size=2gb

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up .env file
        run: |
          echo "ABET_PRIVATE_DIR=/home/abet_private" > .env
          echo "APP_CONTAINERNAME=php_apache" >> .env
          echo "SELENIUM_PORT=4445" >> .env
          echo "MYSQL_DATABASE=testdb" >> .env
          echo "MYSQL_ROOT_PASSWORD=testingRootPassword" >> .env
          echo "MYSQL_USER=testingUser" >> .env
          echo "MYSQL_PASS=testingPassword" >> .env
        working-directory: ./docker

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install testing dependencies
        run: |
          pip install --root-user-action=ignore -r src/test/requirements.txt > /dev/null

      - name: kill any running docker containers (cleanup)
        working-directory: ./docker
        run: |
          docker compose --profile testingdown || true

      - name: run docker compose to start the application 
        working-directory: ./docker
        run: |
          docker compose up -d 

      - name: connect service to our containers
        run: |
          docker network connect app_network selenium || true

      - name: Run Selenium tests
        run: |
          # Wait for the Selenium container to be ready
          sleep 20
          # Run your Selenium tests here, for example:
          pytest src/test/